name: Keep FastAPI Backend Warm

on:
  schedule:
    - cron: "*/1 * * * *" 
  workflow_dispatch:

jobs:
  ping-api:
    runs-on: ubuntu-latest
    steps:
      - name: Ping FastAPI health route
        run: |
            echo "Calling: https://maamla-legal-hai-api.onrender.com/health?token=${{ secrets.HEALTH_CHECK_TOKEN }}"
            curl -v "https://maamla-legal-hai-api.onrender.com/health?token=${{ secrets.HEALTH_CHECK_TOKEN }}"
